### ISSUE TITLE
Building Permit stuck in Pending issuance 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#186]
258063 is stuck in pending issuance for he capacity permit to be related and complete... which it is. there is also a hold for child permit must be issued.. there is no other child permit?
![image](https://user-images.githubusercontent.com/47611580/71906894-ffeeef80-3138-11ea-80e4-a1a008f40846.png)

**Comment by calequin** [comment]
The formula is looking to see if the child permit is finalized. In this case the capacity permit is issued but not finalized. @ABonomo21 do we need to change the code to only look at issued and not finalized?

If ChildBLD.ChildApplication.FinalizedDateTime = DateTime.MinValue Then

		StateCheck = True

**Comment by calequin** [comment]
capacity needs to be issued and not finalized.

**Comment by calequin** [comment]
promote BP_CheckChildrenareFinal_SCF

**Comment by calequin** [comment]
promoted 1.8.2020

**Comment by ABonomo21** [comment]
re- opening ticket, 
see attached this permit was stuck in pending issuance for the capacity permit not being complete but the capacity permit is issued. 
![image](https://user-images.githubusercontent.com/47611580/72629469-671d5880-391e-11ea-98ff-339b342fc5ef.png)
![image](https://user-images.githubusercontent.com/47611580/72629498-77cdce80-391e-11ea-97e6-e193cb99bd36.png)
![image](https://user-images.githubusercontent.com/47611580/72629521-81efcd00-391e-11ea-982e-40d8aa5d33e0.png)

**Comment by calequin** [comment]
fixed in test. once accepted please promote formula : BP_CAPACITYPermitRelated_SCF

**Comment by ABonomo21** [comment]
Still not working: 196961 

![image](https://user-images.githubusercontent.com/47611580/72899805-c00d3800-3cf4-11ea-979d-72f6a3ebfcc9.png)
![image](https://user-images.githubusercontent.com/47611580/72899817-c4d1ec00-3cf4-11ea-83cf-1052306aa4ad.png)

1/22/2020 EP

**Comment by calequin** [comment]
This needs to be tested in test and then deployed. Looks like it was tested against prod which is not updated yet

**Comment by ABonomo21** [comment]
tested 259390

**Comment by awhite806** [comment]
RE-OPENING- PERMIT #258340 was stuck in pending issuance with the hold of "capacity permit must be related and completed." the capacity permit needs to be issued not completed for the building permit to issue. 
![image](https://user-images.githubusercontent.com/58981029/74458820-429e9880-4e58-11ea-9fa8-7bd03bb88786.png)
![image](https://user-images.githubusercontent.com/58981029/74458828-45998900-4e58-11ea-946f-706d814e32ad.png)

**Comment by calequin** [comment]
please test and once accepted promote
BP_CAPACITYPermitRelated_SCF

**Comment by ABonomo21** [comment]
tested 263366 and it worked thanks

**Comment by calequin** [comment]
promoted on 2.23.2020
