### ISSUE TITLE
PLANNING - NOTIFICATION for Recordation

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#284]
The AP number - PL257733
The observed behavior - Plat Recordation Email - not generating recordation information
The expected behavior - Plat Recordation Email - should generate recordation information

![image](https://user-images.githubusercontent.com/58854333/73197034-a7d75780-40fe-11ea-9957-8479fc1648ab.png)

**Comment by JuanitaMiles** [comment]
IPS TEST Upgrade ticket. Assigning to Dan.

**Comment by megisys** [comment]
No This is not a Upgrade Issue - Production Issue.

**Comment by megisys** [comment]
PlanningPlatNotifications - Move SendNotifications

**Comment by JuanitaMiles** [comment]
Dan Updated PLN_FINAL. Ready for Retest

**Comment by MLWilkins** [comment]
the language is cleaned up but this notification is suppose to include the plat book and page number from the final plat details.  R4C does not show the plat book and page number.  This was discussed at length before go-live and the solution that was provided to us was to have the platbook and page number show on the notification. 

As is, the notification is sending people to the portal for information but the information they are looking for isnt there.  This will result in us getting calls and emails.

**Comment by calequin** [comment]
fixed in test. changed the notification template PLN_FINAL to reflect the correct business object.

**Comment by MLWilkins** [comment]
getting two different recordation emails now.  Only need one.  Also while two emails were received nothing is showing up in the log. I did a final plat (PL257705) and it was fine.  The problems originally posted in this ticket and the retest shots below are from addition plats.
 
![image](https://user-images.githubusercontent.com/50637067/73560429-f0f01a00-4424-11ea-85b0-f2d4f2f9fba8.png)

![image](https://user-images.githubusercontent.com/50637067/73560565-36ace280-4425-11ea-969b-ba1fe9dbeb07.png)

![image](https://user-images.githubusercontent.com/50637067/73560601-44626800-4425-11ea-90e5-8b7df6bb4329.png)


![image](https://user-images.githubusercontent.com/50637067/73560770-960af280-4425-11ea-9ae1-7fa50550808f.png)

**Comment by calequin** [comment]
Fixed in test once accepted please promote the following:
Application Workflow PLAW - PLAT > Conditions > Expire SYS_FINAL
promote formula fix - SYS_AddCommunicationAsLog

**Comment by MLWilkins** [comment]
still getting two notifications. One called Redecoration Details and one called Plat Redecoration Details.  The plat recordation details notification is bad.  Remove this notification and just have the Recordation details one send out.

Also, the LOG does not show two recordation notifications going out but as you can see I received two emails.

 
![image](https://user-images.githubusercontent.com/50637067/73742702-001fe200-471b-11ea-881f-43fb18fc387e.png)

![image](https://user-images.githubusercontent.com/50637067/73742643-db2b6f00-471a-11ea-91ad-61d6285e570a.png)

![image](https://user-images.githubusercontent.com/50637067/73742665-ebdbe500-471a-11ea-9750-44298a1a3933.png)

**Comment by MLWilkins** [comment]
got one email, thats good.  But its not showing up as sent in the log.  Please check fixes before marking for retest.


![image](https://user-images.githubusercontent.com/50637067/73772377-07141800-474e-11ea-8b9d-9e87323d7e16.png)


![image](https://user-images.githubusercontent.com/50637067/73772415-172bf780-474e-11ea-8c2f-511a7ec01116.png)

**Comment by calequin** [comment]
fixed and tested by me in test. once accepted please promote
SYS_AddCommunicationAsLog

**Comment by MLWilkins** [comment]
test confirmed on PL258798.  One email sent and it shows in log

**Comment by calequin** [comment]
promoted on 2.9.2020

**Comment by MLWilkins** [comment]
same old problem came back.  WHY DOES THIS KEEP HAPPENING?  This happened on PL257647 and PL257653

![image](https://user-images.githubusercontent.com/50637067/75569145-93022280-5a22-11ea-86a7-a6316767a0e9.png)

**Comment by JuanitaMiles** [comment]
@pooldaddy This is an item that Mike and Ashley have worked extensively with Dan and Christian on...but it appears the problem of two different types of emails are going out for plat recordation has returned. You can see in the logs that the PLAT Recordation Notification sent and the Final RecordationNotification sent as well. From looking at the comments above, the "PLAT Recordation Notification" should be the only one that sends. The Final Recordation Notification should be eliminated.

**Comment by megisys** [comment]
PLN_NotificaitonFinal_AOC needs to be Disabled in Production

**Comment by MLWilkins** [comment]
fixed


![image](https://user-images.githubusercontent.com/50637067/76530315-f2602980-6449-11ea-8e80-0e7729648658.png)

![image](https://user-images.githubusercontent.com/50637067/76530397-0d329e00-644a-11ea-894f-744ea50b2a32.png)
