### ISSUE TITLE
GIS - Join Addresses Tool Error

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#322]
Mary McCullough tried using the Join Addresses tool on 6216 and 6216 C Woodville. After running the tool she now gets an error and cannot access the address. This is the only address Mary has tried using the tool on.

Steps to replicate:
Resources> Lookup Addresses (RLA)> Searched on Woodville RD > Checked both 6216 and 6216 C Woodville > Action > Join Addresses 

![image](https://user-images.githubusercontent.com/31770504/73552235-debaaf80-4415-11ea-9f75-98061fac0195.png)

**Comment by calequin** [comment]
@JuanitaMiles spoke to Dan about this. The joining addresses tool in ips only creates a version of the address and does not merge. Dan needs to develop a tool for merging of addresses. The estimated hours are 40 hours for this enhancement.

**Comment by JuanitaMiles** [comment]
@calequin ok but how do we fix the error Mary is getting for the 6212 C Woodville address? We can't have the address inaccessible in the system if it is needed.

**Comment by JuanitaMiles** [comment]
In addition, the Infor Help documentation indicates that merging is the intended use of the Join Addresses tool. It sounds like the current tool needs to be fixed rather than a new one be developed.

![image](https://user-images.githubusercontent.com/31770504/73563270-ec2e6480-442a-11ea-9ca6-51c6579e27b1.png)

**Comment by megisys** [comment]
PLease Try this again.. Missing entries in the Agency Table

**Comment by JuanitaMiles** [comment]
@megisys Can you please fix the error that is occuring on the 6212 C Woodville Address. Mary is not willing to test on another address if we don't know this error can be fixed. Thanks.

**Comment by megisys** [comment]
It is ready for you to test.. I fixed this already this was our test transaction we used

**Comment by JuanitaMiles** [comment]
If your test transaction was merging 6212 C Woodville into 6212 Woodville in the test environment, an error is still occurring when trying to click on 6212 Woodville. (Mary was trying to merge 6212 into 6212 C) Doesn't appear fixed to me.

![image](https://user-images.githubusercontent.com/31770504/73943908-a573bb00-48bf-11ea-9691-494fe28f1df3.png)

![image](https://user-images.githubusercontent.com/31770504/73943982-c63c1080-48bf-11ea-920a-c9320931932b.png)

The error in Production is still sitting on the 6212 C Woodville address as well. 

![image](https://user-images.githubusercontent.com/31770504/73944207-2df25b80-48c0-11ea-8b7d-59866ac408ae.png)

![image](https://user-images.githubusercontent.com/31770504/73944243-3e0a3b00-48c0-11ea-972c-d2b341ee664b.png)

**Comment by megisys** [comment]
It seems we accidentally inserted 2 new record into the Address Detail Extension table for that address. This has been removed in TEST.  Please do a few more merges and let me see if this is a problem with the out of the box tool.  The out of the box tool will not know how to handle address extension tables.

**Comment by megisys** [comment]
Question has to be asked.. Which Extension table should be retained in a case of merge. and what are you going to do about associated parcels.

**Comment by JuanitaMiles** [comment]
Mary tested this again in test per the email chain we had going. Tried to forward this to you through the email, but people are responding to various spots in the email chain rather than the latest version, it's messy. Nonetheless...She saw no change in the issue. See the addresses tested in the screenshot below.

![image](https://user-images.githubusercontent.com/31770504/73967556-1ded7280-48e6-11ea-8b47-16532faa60b6.png)

**Comment by megisys** [comment]
This is due to the out of the box tool not understanding your requirements. It is too generic as I mentioned. A custom tool may need to be written or a large workaround applied.. Please let me know the priority here.

**Comment by megisys** [comment]
Email send directly to Mary and Team

**Comment by megisys** [comment]
Issue is with Mary to test in test

**Comment by megisys** [comment]
PLease promote TESTERproperty - But please name AgencyCDR_RetainDetailPage_BUF

**Comment by calequin** [comment]
added formula and promoted on 2.23.2020

**Comment by JuanitaMiles** [comment]
Reopening per Mary's request. She has identified the following error in Prod with the Delete tool.

![image](https://user-images.githubusercontent.com/31770504/75189747-d99f0680-571c-11ea-99ae-a55b3430107d.png)

![image](https://user-images.githubusercontent.com/31770504/75189812-fd624c80-571c-11ea-95d9-fb67fceb8af0.png)

![image](https://user-images.githubusercontent.com/31770504/75189852-1965ee00-571d-11ea-8616-c92aaec95cbd.png)

**Comment by JuanitaMiles** [comment]
Dan emailed 2/24 requesting that an Infor Extreme ticket be submitted for Mary's latest issue with the delete tool as the strategy to delete data is not the recommended best practice. Unassigning Dan for now until we receive a response.

**Comment by ABonomo21** [comment]
possible product enhancement discussion to be had closing for now
