### ISSUE TITLE
Notification Issue

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#415]
![image](https://user-images.githubusercontent.com/47611580/74657106-87c71100-515d-11ea-8bea-5aa73c761779.png)

![image](https://user-images.githubusercontent.com/47611580/74657128-9281a600-515d-11ea-8ebe-3201a781bc7b.png)

Abbie received the notification for building permit 264545 log shows it did not go to the customer??

**Comment by awhite806** [comment]
Another few...seems to be every permit processed this morning.
![image](https://user-images.githubusercontent.com/58981029/74659603-a1b72280-5162-11ea-81c2-5d1ab34b14fd.png)
![image](https://user-images.githubusercontent.com/58981029/74659624-af6ca800-5162-11ea-88a2-b9b9f94a9c55.png)
![image](https://user-images.githubusercontent.com/58981029/74659657-bbf10080-5162-11ea-9a53-a73c950fe790.png)

**Comment by megisys** [comment]
Small Change. Hopefully didn't cause too much disruption.  Let me know if they are flowing again

**Comment by awhite806** [comment]
This is still occurring as of 2/18/2020 730AM. 
![image](https://user-images.githubusercontent.com/58981029/74741593-19508480-522b-11ea-96a0-0abfb2e816db.png)
![image](https://user-images.githubusercontent.com/58981029/74741626-29686400-522b-11ea-8c8f-e7acea86d7ca.png)

**Comment by awhite806** [comment]
They're are also duplicate emails being sent. Some are going to customers but most are being sent to Permits Staff
![image](https://user-images.githubusercontent.com/58981029/74741762-65032e00-522b-11ea-8240-61721c443e0d.png)
![image](https://user-images.githubusercontent.com/58981029/74741809-78ae9480-522b-11ea-9fbf-9d5030c70f23.png)

**Comment by JuanitaMiles** [comment]
![image](https://user-images.githubusercontent.com/31770504/74742491-b3fd9300-522c-11ea-90f9-9c0808e21e6e.png)

**Comment by ABonomo21** [comment]
There is a error now in mobile when trying to result building finals for notifications as well @megisys @calequin 
![image](https://user-images.githubusercontent.com/47611580/74763524-fbe0e200-524d-11ea-8d0e-c6de3d5bb724.png)

**Comment by ABonomo21** [comment]
Inspectors cannot result building finals in the field on mobile.

**Comment by megisys** [comment]
Addressed in other Ticket

**Comment by JuanitaMiles** [comment]
Ashlye reported that this is still a problem as of yesterday. Ashlye to send examples of this from yesterday to Christian.

**Comment by calequin** [comment]
Email sent out about notification ad hoc that allows staff to view which notifications went out and to whom.

Hi Team,
We created an adhoc report that can be added to your dashboard for notifications called Email Notifications and it is housed under the Common Group. This will give you a look into what notifications have been sent out, recipient, delivery result and record #. Please add this to your dashboard to help understand which emails have gone out and if it has gone out multiple times etc. Also, while running this report I did not see any emails going out to county staff today or yesterday. Please send me examples so that I can troubleshoot.

Thanks,

**Comment by JuanitaMiles** [comment]
@ABonomo21 Please close if no additional instances of staff getting emails has occurred in the last day or two. If it has, provide some examples.

**Comment by ABonomo21** [comment]
checked with staff they have not received any emails.
